version: "3.4"

services:
  locationservice:
    image: locationapi
    container_name: location
    build:
      context: .
      dockerfile: LocationAPI/Dockerfile
    environment:
      ConnectionString: "Server=sql;Database=Location;Trusted_Connection=False;User Id=sa;Password=password1!;MultipleActiveResultSets=true"
    ports:
      - "8998:80"
    networks:
      - dm-network
  sql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sql
    environment:
      SA_PASSWORD: "password1!"
      ACCEPT_EULA: "Y"
    networks:
      - dm-network
    ports:
      - "1402:1433"
    volumes:
      - sqlvolume:/var/opt/mssql 
networks:
  dm-network:
    driver: bridge
volumes:
  sqlvolume:
    name: sqldata